services:

  # =====================
  #  FLASK APPLICATION
  # =====================
  web:
    container_name: flask-web
    build:
      context: ../../app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - sqlite-data:/app/instance
    networks:
      - internal_net
      - public_net
    restart: unless-stopped
    labels:
      - "prometheus.job=flask"
      - "prometheus.scrape=true"
      - "prometheus.port=5000"
      - "prometheus.path=/metrics"

  # =====================
  #  PROMETHEUS
  # =====================
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal_net
      - public_net
    restart: unless-stopped

  # =====================
  #  GRAFANA
  # =====================
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - internal_net
      - public_net
    restart: unless-stopped

# =====================
#  VOLUMES
# =====================
volumes:
  sqlite-data:
  grafana-data:

# =====================
#  NETWORKS
# =====================
networks:
  internal_net:      # сервисы общаются друг с другом
  public_net:        # всё что должно быть доступно снаружи
