services:
  web:
    container_name: flask-web
    build:
      context: ../../app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - sqlite-data:/app/instance
    networks:
      - app_default
      - monitoring
    restart: unless-stopped

volumes:
  sqlite-data:

networks:
  app_default:
  monitoring:
    external: true
